name: builds
on: [push, pull_request]

jobs:
  makefile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y util-linux libmount-dev libfuse-dev libzstd-dev
          wget https://github.com/simonpintarelli/squashfuse/archive/refs/tags/0.1.105-mt.tar.gz && tar xf 0.1.105-mt.tar.gz
          cd squashfuse-0.1.105-mt || exit 1
          ./autogen.sh && ./configure --prefix=/usr --enable-multithreading  && sudo make install
      - name: build
        run: |
          sudo make install-suid
      - name: test
        run: . ci/test-mount.sh
  meson:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build util-linux libmount-dev libfuse-dev libzstd-dev
          wget https://github.com/simonpintarelli/squashfuse/archive/refs/tags/0.1.105-mt.tar.gz && tar xf 0.1.105-mt.tar.gz
          cd squashfuse-0.1.105-mt || exit 1
          ./autogen.sh && ./configure --prefix=/usr --enable-multithreading  && sudo make install
          # can't install as user because we need `sudo meson install` later
          sudo pip3 install meson
      - name: build
        run: |
          meson setup -Dfuse_version=fuse -Dsuid=true build
          meson compile -C build
          sudo meson install -C build
      - name: test
        run: . ci/test-mount.sh
  meson-nonsuid:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build util-linux libmount-dev libfuse-dev libzstd-dev
          wget https://github.com/simonpintarelli/squashfuse/archive/refs/tags/0.1.105-mt.tar.gz && tar xf 0.1.105-mt.tar.gz
          # wget https://github.com/vasi/squashfuse/archive/refs/tags/0.1.105.tar.gz && tar xf 0.1.105.tar.gz
          cd squashfuse-0.1.105-mt || exit 1
          ./autogen.sh && ./configure --prefix=/usr --enable-multithreading  && sudo make install
          # can't install as user because we need `sudo meson install` later
          sudo pip3 install meson
      - name: build
        run: |
          meson setup -Dfuse_version=fuse -Dsuid=false build
          meson compile -C build
          sudo meson install -C build
      - name: test
        run: . ci/test-mount.sh
